version: '3.8'
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chrome
    privileged: true
    environment:
      - TITLE=chrome
      - DISPLAY=:1
      - PUID=1000
      - PGID=1000
      - CUSTOM_USER=${USERNAME}
      - PASSWORD=${PASSWORD}
      - LANGUAGE=ru_RU.UTF-8
      - CHROME_CLI=
    volumes:
      - ${HOME}/chromium/config:/config
    ports:
      - "0.0.0.0:${PORT}:3000"  
    shm_size: '4gb'
    restart: unless-stopped
